spring:
  application:
    name: billing-payment

  config:
    import: optional:configserver://

  datasource:
    password: 'eSFHR9u2mbBVLLDJtSG3'
    url: jdbc:postgresql://149.56.107.189:5432/db_formation
    username: 'root'

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    init-sqls: SET ROLE root
    schemas: payment

server:
  port: 8081
