spring:
  application:
    name: billing-payment
#  cloud:
#    vault:
#      uri: http://localhost:32768/
#      token:
#      kv:
#        enabled: true
#        backend: secret
#        default-context: application

  datasource:
    url: jdbc:postgresql://149.56.107.189:5432/db_formation
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver://
  flyway:
    enabled: true
    schemas: payment
    default-schema: payment
    baseline-on-migrate: true
    locations: classpath:db/migration