server:
  port: 8082

spring:
  application:
    name: billing-payment


  config:
    import:
      - optional:vault://


  cloud:
    config :
      enabled: false
    vault:
      uri: http://localhost:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:root}
      kv:
        enabled: true
        backend: secret
        default-context: billing-payment
        application-name: billing-payment

  datasource:
    url: jdbc:postgresql://149.56.107.189:5432/db_formation
    username: root
    password: eSFHR9u2mbBVLLDJtSG3
    driver-class-name: org.postgresql.Driver
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    schemas: payment
    default-schema: payment
    baseline-on-migrate: true
    locations: classpath:scripts

  rabbitmq:
    host: 149.56.107.189
    port: 5672
    username: admin
    password: AgQH5EFSTk8QeHNFwG3c
    listener:
      simple:
        # Retry automatique avant envoi en DLQ
        retry:
          enabled: true
          initial-interval: 2000    # 2s avant 1er retry
          multiplier: 2             # backoff exponentiel
          max-attempts: 3           # 3 tentatives max
          max-interval: 10000       # plafond 10s
        acknowledge-mode: auto # nack automatique en cas d'exception

camunda.bpm.admin-user:
   id: demo
   password: demo

app:
  feign-clients:
    reference-service:
      name: billing-invoice
      url: http://localhost:8080