-- =========================================
-- V2: UPDATE TRANSACTION TABLE
-- =========================================

ALTER TABLE payment."TRANSACTION"
    ADD COLUMN PV_ID BIGINT;

ALTER TABLE payment."TRANSACTION"
    ADD COLUMN CREANCIER_ID BIGINT;

ALTER TABLE payment."TRANSACTION"
    DROP COLUMN DATE;

CREATE INDEX IDX_TRANSACTION_PV_ID
    ON payment."TRANSACTION"(PV_ID);

CREATE INDEX IDX_TRANSACTION_CREANCIER_ID
    ON payment."TRANSACTION"(CREANCIER_ID);